export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_POST_REQUEST = "BLOG_POST_REQUEST";
export const BLOG_POST_SUCCESS = "BLOG_POST_SUCCESS";
export const BLOG_POST_FAIL = "BLOG_POST_FAIL";
