export const TUTORIAL_LIST_REQUEST = "TUTORIAL_LIST_REQUEST";
export const TUTORIAL_LIST_SUCCESS = "TUTORIAL_LIST_SUCCESS";
export const TUTORIAL_LIST_FAIL = "TUTORIAL_LIST_FAIL";

export const TUTORIAL_PAGE_REQUEST = "TUTORIAL_PAGE_REQUEST";
export const TUTORIAL_PAGE_SUCCESS = "TUTORIAL_PAGE_SUCCESS";
export const TUTORIAL_PAGE_FAIL = "TUTORIAL_POST_FAIL";
